### ISSUE TITLE
Incompatibility Crash

### ISSUE THREAD

**Issue by Wash113** [juancarloscp52/BedrockIfy#356] opened 2024-07-12 23:45 UTC
Hey there!

So I have been running down a crash that occurred last night. This seems to be an incompatibility with Easy Shulker Boxes by Fusz and/or an incompatibility with Friends and Foes.

I had found a rascal from Friends and Foes and completed his game. As the reward, he tossed me a bundle. Immediately upon the bundle entering my inventory, the game crashed. This persisted until I deleted the bundle from my inventory via NBTExplorer. I initially thought the error originated from Easy Shulker Boxes, but Fusz took a look and found the issue. He has highlighted the problem in the following thread. Hope youre having a great day!

https://github.com/Fuzss/easyshulkerboxes/issues/54#issuecomment-2224960424

[Crash Report](https://mclo.gs/TDamJmh)

**Comment by Nuzza** [comment] 2024-07-13 03:06
This is a duplicate of [issue #326](https://github.com/juancarloscp52/BedrockIfy/issues/326)

**Closed as completed** 2024-07-30 14:52 UTC
