### ISSUE TITLE
[Mod conflict] Crashes with Skin Swapper

### ISSUE THREAD

**Issue by K0-RR** [juancarloscp52/BedrockIfy#36] opened 2020-12-11 10:28 UTC
Reported to Skin Swapper - https://github.com/cobrasrock/Skin-Swapper/issues/7
crash report - https://hatebin.com/gqobhslpas
latest.log - https://hatebin.com/pgzchhyavd

**Comment by juancarloscp52** [comment] 2020-12-11 11:20
Hi! try the temporal fix purposed in #33. I'll try to upload a real fix for this issue later this month.

**Comment by juancarloscp52** [comment] 2020-12-29 20:45
The cause of this crash has been fixed in the latest BedrockIfy version. You should be able to use Panorama Background with this mod without any crashes!

**Closed as completed by juancarloscp52** 2020-12-29 20:45 UTC
Labels: bug, mod incompatibility
