### ISSUE TITLE
The panoramic menu does not move urgently!

### ISSUE THREAD

**Issue by ghost** [juancarloscp52/BedrockIfy#73] opened 2021-05-05 15:56 UTC
fter installing the mod, starting from version 0.2.3 the panoramic menu stopped moving
You tobish the background

**Comment by K0-RR** [comment] 2021-05-05 16:32
Duplicate of https://github.com/juancarloscp52/BedrockIfy/issues/50

**Comment by juancarloscp52** [comment] 2021-05-06 20:11
@MiFliK please check and try: https://github.com/juancarloscp52/BedrockIfy/issues/50#issuecomment-833827217

**Closed as completed** 2021-06-08 20:37 UTC
Labels: bug, duplicate
