### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by Arthurmeade12** [juancarloscp52/BedrockIfy#166] opened 2022-07-24 15:06 UTC
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/24/22, 11:04 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bedrockify'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:worldgen/configured_feature / bedrockify:dying_birch_tree])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.fabricmc.fabric.impl.registry.sync.DynamicRegistrySync.lambda$setupSync$1(DynamicRegistrySync.java:64)
	at net.minecraft.class_2370.mdc44421$lambda$new$0$5(class_2370.java:597)
	at net.minecraft.class_2370.handler$cop000$setPost(class_2370.java:675)
	at net.minecraft.class_2370.method_31051(class_2370.java:130)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_2378.method_39197(class_2378.java:508)
	at net.minecraft.class_2378.method_10230(class_2378.java:504)
	at me.juancarloscp52.bedrockify.common.features.worldGeneration.DyingTrees.registerDyingTrees(DyingTrees.java:66)
	at me.juancarloscp52.bedrockify.common.features.worldGeneration.DyingTrees.registerTrees(DyingTrees.java:59)
	at me.juancarloscp52.bedrockify.Bedrockify.onInitialize(Bedrockify.java:28)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 18.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 372941752 bytes (355 MiB) / 1249902592 bytes (1192 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel UHD Graphics 617
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x87c0
	Graphics card #0 versionInfo: Revision ID: 0x0002
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 5052.09
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 174.25
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
		adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
		animatica: Animatica 0.5+1.19
		antighost: AntiGhost 1.19-fabric0.55.3-1.1.5
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.10.33
		authme: Auth Me 4.0.0
		autoswitch: AutoSwitch 5.1.3-alpha.1
		autoswitch-api: AutoSwitch API 1.1.0
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.3.0+0
		bedrockify: BedrockIfy 1.4.2+mc1.19
		bedrockskinutility: BedrockSkinUtility 1.3.0
		betterf3: BetterF3 1.3.2
		bettermounthud: Better Mount HUD 1.1.4
		blockify: Blockify 1.2.3
		blue_endless_jankson: jankson 1.2.1
		boathud: BoatHud 1.1.1
		boatiview: Boat Item View Fabric 0.0.3
		borderlessmining: Borderless Mining 1.1.5+1.19
		brb: Better Recipe Book 1.6.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.8.2
		c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.8.2
		c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.8.2
		c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.8.2
		c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.8.2
		c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.8.2
		c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.8.2
		c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.8.2
		c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.8.2
		c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.8.2
		c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.8.2
		c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.8.2
		c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.8.2
		c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.8.2
		c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.8.2
		c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.8.2
		c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.8.2
		c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
		c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.8.2
		c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.8.2
		c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
		caffeineconfig: CaffeineConfig 1.0.0+1.17
		capes: Capes 1.4.4+1.19
		cem: Custom Entity Models 0.7.1
		charmonium: Charmonium 4.1.0
		chesttracker: Chest Tracker 1.1.17
		chunky: Chunky 1.2.217
		citresewn: CIT Resewn 1.1.1+1.19
		citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
		clientarguments: clientarguments 1.4.1
		clientcommands: Client Commands 2.7
		clienttweaks: Client Tweaks 8.0.0
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 7.0.73
		cloud: Cloud 1.7.0
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.7.0
		cloud_commandframework_cloud-core_: cloud-core 1.7.0
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.7.0
		cloud_commandframework_cloud-services_: cloud-services 1.7.0
		colormatic: Colormatic 3.1.2+mc.1.19
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_github_llamalad7_mixinextras: mixinextras 0.0.11
		com_ibm_async_asyncutil: asyncutil 0.1.0
		com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.2
		completeconfig-base: completeconfig-base 2.0.0-beta.3
		completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		conditional-mixin: conditional mixin 0.3.0
		confabricate: confabricate 3.0.0-SNAPSHOT+4.1.2
		continuity: Continuity 2.0.0+1.19
		cr-compass-ribbon: Chrono's Compass Ribbon 2.8.2+1.19
		crowdin-translate: CrowdinTranslate 1.4+1.19
		cull-less-leaves: Cull Less Leaves 1.0.4
		darkgraph: Dark Graph 1.0.2
		debugify: Debugify 2.3.2
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		dev_isxander_settxi_settxi-core: settxi-core 2.4.0
		dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.4.0
		dynamicfps: Dynamic FPS 2.2.0
		easiercrafting: EasierCrafting 1.19-fabric0.53.3-1.7
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
		entity_texture_features: Entity Texture Features 3.1.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabrishot: Fabrishot 1.8.0
		ferritecore: FerriteCore 4.2.1
		fvt: Flour's Various Tweaks 1.11.0-mc1.19
		gbfabrictools: GBfabrictools 1.3.4+1.19
		indium: Indium 1.0.6+mc1.19
		inventoryprofilesnext: Inventory Profiles Next 1.6.1
		invmove: InvMove 0.8.0
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		iris: Iris 1.2.5
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jankson: Jankson 4.1.1+j1.2.1
		java: OpenJDK 64-Bit Server VM 18
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
		languagereload: Language Reload 1.3.1
		lazydfu: LazyDFU 0.1.3
		libgui: LibGui 6.0.0-beta.5+1.19-pre1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.8.1
		mcmouser: McMouser 1.19-fabric-1.0.0
		memoryleakfix: memory Leak Fix 1.19-0.5.4
		midnightcontrols: MidnightControls 1.4.1+1.19
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		mixin-conflict-helper: Mixin Conflict Helper 1.1.0
		moderate-loading-screen: Mod-erate Loading Screen 1.1.3+1.19
		modmenu: Mod Menu 4.0.4
		mods-command: Mods Command 1.0.9
		morechathistory: MoreChatHistory 1.1.0
		moreculling: More Culling 1.19-0.6.0
		moremusic: More Music 0.1.3+1.19
		multiconnect-api: MultiConnect API 1.5.10
		net_kyori_adventure-api: adventure-api 4.11.0
		net_kyori_adventure-key: adventure-key 4.11.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.1.0
		net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
		net_kyori_examination-api: examination-api 1.3.0
		net_kyori_examination-string: examination-string 1.3.0
		nmuk: No More Useless Keys 1.0.1+mc1.19
		no-telemetry: No Telemetry 1.4.0
		nochatreports: No Chat Reports 1.19-v1.2.3
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		omega-config: OmegaConfig 1.2.3-1.18.1
		optigui: OptiGUI 1.1.1
		org_aeonbits_owner_owner: owner 1.0.12
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		org_joml_joml: joml 1.10.4
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.2
		org_spongepowered_configurate-gson: configurate-gson 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		org_spongepowered_configurate-yaml: configurate-yaml 4.1.2
		org_threadly_threadly: threadly 7.0
		org_yaml_snakeyaml: snakeyaml 1.31-SNAPSHOT
		petowner: Pet Owner 1.8.3-1.19+
		placeholder-api: Placeholder API 2.0.0-beta.3+1.19
		pride: Pride Lib 1.1.2+1.19
		purpurclient: Purpur Client 1.19-6
		puzzle: Puzzle 1.3.4-1.19
		puzzle-base: Puzzle Base 1.3.4-1.19
		puzzle-gui: Puzzle GUI 1.3.4-1.19
		puzzle-models: Puzzle Models 1.3.4-1.19
		puzzle-splashscreen: Puzzle Splash Screen 1.3.4-1.19
		quilt_advancement: Quilt Advancement API 2.0.0-beta.16+1.19
		quilt_base: Quilt Base API 2.0.0-beta.16+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.16+1.19
		quilt_block_entity: Quilt Block Entity API 2.0.0-beta.16+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.16+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.16+1.19
		quilt_command: Quilt Command API 2.0.0-beta.16+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.16+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.16+1.19
		quilt_item_content_registry: Quilt Item Content Registry API 2.0.0-beta.16+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.16+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.16+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.16+1.19
		quilt_loader: Quilt Loader 0.17.1-beta.6
		quilt_networking: Quilt Networking 2.0.0-beta.16+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.16+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.16+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.16+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.16+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.16+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.16+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.16+1.19
		quilted_fabric_api: Quilted Fabric API 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_base: Quilted Fabric API Base 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 2.0.0-beta.9+0.58.0-1.19
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 2.0.0-beta.9+0.58.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		roughlyenoughitems: Roughly Enough Items 9.1.517
		servercore: ServerCore 1.3.0-1.19
		settxi-gui-cloth-config: Settxi Gui (Cloth Config) 2.4.0
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.4.5
		sodium: Sodium 0.4.2+build.16
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
		spark: spark 1.9.26
		spruceui: SpruceUI 4.0.0+1.19
		starlight: Starlight 1.1.1+fabric.ae22326
		stendhal: Stendhal 1.3.3-1.19
		tooltipfix: ToolTip Fix 1.0.5-1.19
		vmp: Very Many Players 0.2.0+beta.6.27
		vt_downloader: VTDownloader 1.0.8+1.19
		waveycapes: WaveyCapes 1.2.0
		whereisit: Where Is It 1.14.11
		wthit: wthit 5.7.0
		xaerominimap: Xaero's Minimap 22.12.0
		yosbr: YOSBR 0.1.1
		zoomify: Zoomify 1.7.1
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: BedrockIfy (bedrockify), Quilted Fabric Registry Sync (v0) (quilted_fabric_registry_sync_v0), Quilt Loader (quilt_loader), Minecraft (minecraft)
#@!@# Game crashed! Crash report saved to: #@!@# /Users/keith/Library/Application Support/PolyMC/instances/Fabulously Optimized 4.0.0-beta.11/.minecraft/crash-reports/crash-2022-07-24_11.04.04-client.txt

**Comment by juancarloscp52** [comment] 2022-10-13 15:28
Hmm I'm not able to reproduce the crash with that quilt version, maybe a incompatibility with some of the mods installed?  Also working in the newer versions. Please let me know if the issue still occurs.

**Comment by Adriianh** [comment] 2022-12-07 08:02
Hi, I was having this problem too. I found out that the incompatibility is with Purpur Client.

**Comment by juancarloscp52** [comment] 2022-12-17 16:56
In fact was purpur client. Should be fixed with 1.19.3 release. Thanks

**Closed as completed by juancarloscp52** 2022-12-17 16:56 UTC
