### ISSUE TITLE
Crashes with OptiFabric

### ISSUE THREAD

**Issue by Hebgbs** [juancarloscp52/BedrockIfy#136] opened 2022-02-07 02:13 UTC
After some brief investigation which _nobody_ seems to do these days, I've discovered that Bedrockify crashes when using OptiFabric 1.12.10 to load OptiFine 1.18.1_HD_U_H4.

I will append onto this until either Bedrockify functions with OptiFabric or a later version of OptiFine is able to resolve the problem, whatever comes first.

**Comment by juancarloscp52** [comment] 2022-02-07 11:25
Hi! should be fixed with the [latest update](https://www.curseforge.com/minecraft/mc-mods/bedrockify/files/3639882)

**Comment by Hebgbs** [comment] 2022-02-15 12:03
0.13.2

It's happening again. Tried investigating why after Fabric 0.12.12 the game would not open, same copy of OptiFabric, same copy of OptiFine, different Fabric loader. Same shit, different day.

```
[15/02/2022 06:40:42 AM] [Render thread/INFO] Initializing BedrockIfy.
[15/02/2022 06:40:42 AM] [Render thread/INFO] Definitely not up to no good
[15/02/2022 06:40:43 AM] ---- Minecraft Crash Report ----
[15/02/2022 06:40:43 AM] // Why did you do that?
[15/02/2022 06:40:43 AM] 
[15/02/2022 06:40:44 AM] Time: 2/15/22, 6:40 AM
[15/02/2022 06:40:44 AM] Description: Initializing game
[15/02/2022 06:40:44 AM] 
[15/02/2022 06:40:44 AM] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bedrockify'!
```

What's going on here?

_Edit:_ I do not mind staying on 0.12.12 — for now. Just figured I would make you aware the mod isn't happy with OptiFine once more.

**Comment by juancarloscp52** [comment] 2022-02-15 16:16
Hi! I'm not able to reproduce the crash with fabric `0.13.2`, optifabric `1.12.10`, optifine `OptiFine 1.18.1 HD U H4`, and bedrockIfy `1.4.0`
Please send me the full crashlog so I can debug the issue

**Comment by Hebgbs** [comment] 2022-02-15 20:52
I do not know what I was encountering then. Must had been Architectury, because I was having issues with that also.

**Closed as completed** 2022-02-15 21:37 UTC
