### ISSUE TITLE
Newest version incompatible with Java 15, when paired with roughly enough items

### ISSUE THREAD

**Issue by adamf30** [juancarloscp52/BedrockIfy#13] opened 2020-09-29 22:50 UTC
Attempting to run the game with Java 15 when Roughly Enough items is installed alongside crashes the game.
[crash-2020-09-29_17.49.14-client.txt](https://github.com/juancarloscp52/BedrockIfy/files/5302233/crash-2020-09-29_17.49.14-client.txt)

**Comment by juancarloscp52** [comment] 2020-09-30 09:58
Hi! I wasn't able to replicate this bug on my system using Java 15 and REI, but I think I've found the issue anyways.
Could you please try this .jar and tell me if the issue is fixed?
[bedrockify-0.1.4-SNAPSHOT-REI-FIX.zip](https://github.com/juancarloscp52/BedrockIfy/files/5304632/bedrockify-0.1.4-SNAPSHOT-REI-FIX.zip)

**Comment by adamf30** [comment] 2020-09-30 15:59
This fixed the issue for me, yes.

**Comment by adamf30** [comment] 2020-09-30 16:00
![2020-09-30_11 00 17](https://user-images.githubusercontent.com/26857803/94710207-30506c80-030c-11eb-8dcd-feb93d44835c.png) This is more proof...

**Comment by juancarloscp52** [comment] 2020-09-30 16:46
Nice! Thanks for opening this issue!

Fixed in 7ac9474d2052cbe20ea8cd8fc68e5465dd234b97, new version will be released soon.

**Closed by juancarloscp52** 2020-09-30 16:46 UTC
Labels: bug, mod incompatibility
