### ISSUE TITLE
Bedrockify 0.2.3 idle hand animation speed tied to frame rate

### ISSUE THREAD

**Issue by sonopsa** [juancarloscp52/BedrockIfy#55] opened 2021-02-05 06:45 UTC
higher the frame rate the faster the animation

**Comment by juancarloscp52** [comment] 2021-02-05 11:14
Hi! Thanks for opening this issue. I'm unable to reproduce this problem on my system. Could you share a list of mods installed, operating system and Java version? Thanks.

**Comment by sonopsa** [comment] 2021-02-05 22:15
I'm using java version 8.0.2610.12 and windows 10 version 1909. I only have bedrockify-0.2.3 and fabric-api-0.30.0 mods installed

**Comment by juancarloscp52** [comment] 2021-02-06 12:39
Ok, I've located and fixed the issue with d1398874ef9b94868e8828eb69b7f74bca010fe6. Thanks for opening this issue! The fix will be released with the next version of BedrockIfy.

**Closed as completed by juancarloscp52** 2021-02-06 12:39 UTC
Labels: bug
