### ISSUE TITLE
Rainbow Bars while selecting resourcepacks/datapacks

### ISSUE THREAD

**Issue by Raxen1337** [juancarloscp52/BedrockIfy#88] opened 2021-08-07 08:21 UTC
Idk how to name it 
![2021-08-07_10 22 17](https://user-images.githubusercontent.com/86514007/128593947-5287bb49-2aa4-42f0-a448-ef6831c8ca4b.png)
But my eyes hurts
Please fix this

(my english is very bad you may not understand everything)

**Comment by Anoaxx** [comment] 2021-08-15 12:56
it's caused by panorama everywhere.

simple solution: remove panorama from resourcepacks screen or at least option to that, or even better fixed this to look normal xD

**Comment by juancarloscp52** [comment] 2021-08-31 13:34
Fixed in the latest version of bedrockIfy (1.1.2). Thanks for opening this issue.

**Closed as completed by juancarloscp52** 2021-08-31 13:34 UTC
